import type { Unit } from '../types'

export const u001: Unit = {
  id: 1,
  slug: 'zero-article-with-generics',
  title: 'Zero article with generic plurals',
  part: 'noun-phrase',
  level: 'review',
  phenomena: ['zero-article', 'generic-reference'],
  blocks: [
    {
      label: 'A',
      heading: 'The pattern',
      body: [
        { kind: 'p', text: 'When a plural noun refers to a class of things in general, English uses no article at all. This is the zero article.' },
        { kind: 'example', good: 'Neural networks are trained on large corpora.', bad: 'The neural networks are trained on large corpora.', note: 'The bad version says something about a specific, previously identified set of networks.' },
        { kind: 'example', good: 'Rats show a startle response to sudden noise.', bad: 'The rats show a startle response to sudden noise.' },
      ],
    },
    {
      label: 'B',
      heading: 'Uncountable nouns behave the same way',
      body: [
        { kind: 'p', text: 'Uncountable nouns used generically also take no article. Many of these are countable in Portuguese, which is why the article slips in.' },
        { kind: 'list', items: ['evidence', 'research', 'information', 'software', 'equipment', 'literature'] },
        { kind: 'example', good: 'Evidence for this mechanism is still limited.', bad: 'The evidence for this mechanism is still limited.', note: 'Use "the" only when you mean specific evidence already introduced.' },
      ],
    },
    {
      label: 'C',
      heading: 'When "the" is correct after all',
      body: [
        { kind: 'p', text: 'Use "the" when the reference is specific: identified by context, by a modifier, or because it was mentioned before.' },
        { kind: 'example', good: 'The networks we trained in Section 3 converged quickly.', note: 'A relative clause makes the reference specific.' },
        { kind: 'example', good: 'We trained three networks. The networks differed only in depth.', note: 'Second mention.' },
      ],
    },
  ],
  items: [
    { kind: 'gap', id: 'u001.generic-plural.01', phenomenon: 'zero-article',
      context: '____ neural networks are trained on large corpora.',
      answers: [''],
      why: 'Generic plural: no article. Leave the blank empty.' },
    { kind: 'gap', id: 'u001.generic-plural.02', phenomenon: 'definite-article',
      context: '____ networks we trained in Section 3 converged quickly.',
      answers: ['The', 'the'],
      why: 'The relative clause "we trained in Section 3" makes the reference specific, so "the" is required.' },
    { kind: 'gap', id: 'u001.uncountable.03', phenomenon: 'uncountable-nouns',
      context: '____ evidence for this mechanism is still limited.',
      answers: [''],
      why: 'Generic uncountable noun: no article. Portuguese would use "a evidência", which is what pulls the article in.' },
    { kind: 'judge', id: 'u001.judge.04', phenomenon: 'zero-article',
      sentence: 'The transformers have replaced recurrent models in most benchmarks.',
      correct: false,
      why: 'Generic reference to a class of models takes no article: "Transformers have replaced...".' },
    { kind: 'judge', id: 'u001.judge.05', phenomenon: 'generic-reference',
      sentence: 'Rats show a startle response to sudden noise.',
      correct: true,
      why: 'Correct. Generic plural with zero article.' },
    { kind: 'judge', id: 'u001.judge.06', phenomenon: 'uncountable-nouns',
      sentence: 'We collected many informations about the task.',
      correct: false,
      why: '"Information" is uncountable in English: "much information" or "a great deal of information".' },
    { kind: 'choice', id: 'u001.choice.07', phenomenon: 'definite-article',
      prompt: 'We ran three models. ___ models differed only in depth.',
      options: ['The', 'A', '(no article)'],
      correct: 0,
      why: 'Second mention of an already-introduced set, so the reference is specific.' },
    { kind: 'choice', id: 'u001.choice.08', phenomenon: 'zero-article',
      prompt: '___ research on this topic has accelerated since 2020.',
      options: ['The', 'A', '(no article)'],
      correct: 2,
      why: 'Generic uncountable noun. "The research" would mean a specific body of work already identified.' },
    { kind: 'transform', id: 'u001.transform.09', phenomenon: 'zero-article',
      instruction: 'Rewrite so that the sentence refers to convolutional networks in general.',
      source: 'The convolutional networks are sensitive to input scale.',
      answers: ['Convolutional networks are sensitive to input scale.'],
      why: 'Drop the article to move from a specific set to the class as a whole.' },
    { kind: 'errorHunt', id: 'u001.errorhunt.10', phenomenon: 'uncountable-nouns',
      text: 'We reviewed the literatures on neonatal EEG before designing the protocol.',
      span: [16, 27],
      fix: 'literature',
      why: '"Literature" in the scholarly sense is uncountable and has no plural form.' },
  ],
}
